### ISSUE TITLE
Filters do not appear

### ISSUE THREAD

**Issue by EmeraudeIzenah** [kathyisawesome/wc-mnm-filter#15]
Hello, 

The filters don't appear on my page. When I inspect my page, I see the tag but it's in display: none; 
By forcing the CSS, I can display them, but when I click on them, nothing happens.  Maybe I've misconfigured something, I don't understand...

Thanks !

https://www.belloukaz.fr/?product=babyloukaz

**Comment by helgatheviking** [comment]
It's because you have installed the plugin from trunk and not from a release asset. So the necessary script is not included and throwing a 404. 
```
https://www.belloukaz.fr/wp-content/plugins/wc-mnm-filter-trunk/assets/js/frontend/wc-mnm-filter.min.js?ver=2.2.0
```

You should delete the plugin and [download the zip from the latest asset](https://github.com/kathyisawesome/wc-mnm-filter/releases/latest) and install that instead.

**Comment by EmeraudeIzenah** [comment]
Oh yes, thank you very much!
